iching/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ichingdb/', include('ichingdb.urls')),
    path('admin/', admin.site.urls),
]

ichingdb/urls.py
from django.urls import path

from . import views

app_name = 'ichingdb'
urlpatterns = [
    # ex: /ichingdb
    path('', views.index, name='index'),
    # ex: /ichingdb/cast
#    path('cast/', views.ConsultationCreate.as_view(), name='cast'),
    # ex: /ichingdb/random
    path('random/', views.ConsultationCreateRandom.as_view(), name='random'),
    # ex: /ichingdb/5/
    path('<int:cid>/', views.reading, name='reading'),
    # ex: /ichingdb/5/update/
#    path('<int:pk>/update/', views.ConsultationUpdate.as_view(), name='update'),
    # ex: /ichingdb/5/delete/
#    path('<int:pk>/delete/', views.ConsultationDelete.as_view(), name='delete'),
    # ex: /ichingdb/explore
    path('explore/', views.explore, name='explore'),
    # ex: /ichingdb/5/10/
    path('<int:hid>/<int:rid>/', views.reading2, name='reading2'),
    # ex: /ichingdb/related
    path('related/', views.related, name='related'),
    # ex: /ichingdb/paths
    path('paths/', views.paths, name='paths'),
    # ex: /ichingdb/archive
    path('archive/', views.archive, name='archive'),
    # ex: /ichingdb/about
    path('about/', views.about, name='about'),
    # ex: /ichingdb/lowerstatic
    path('lowerstatic/', views.lowerstatic, name='lowerstatic'),
    # ex: /ichingdb/upperstatic
    path('upperstatic/', views.upperstatic, name='upperstatic'),
    # ex: /ichingdb/lowerchanging
    path('lowerchanging/', views.lowerchanging, name='lowerchanging'),
    # ex: /ichingdb/upperchanging
    path('upperchanging/', views.upperchanging, name='upperchanging'),
    # ex: /ichingdb/path01
    path('path01/', views.path01, name='path01'),
    # ex: /ichingdb/path02
    path('path02/', views.path02, name='path02'),
    # ex: /ichingdb/path03
    path('path03/', views.path03, name='path03'),
    # ex: /ichingdb/hextable
    path('hextable/', views.hextable, name='hextable'),
]

ichingdb/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Consultation(models.Model):
    consultation_id = models.AutoField(primary_key=True)
    query = models.CharField(max_length=500)
    line_1 = models.IntegerField()
    chng_1 = models.IntegerField()
    line_2 = models.IntegerField()
    chng_2 = models.IntegerField()
    line_3 = models.IntegerField()
    chng_3 = models.IntegerField()
    line_4 = models.IntegerField()
    chng_4 = models.IntegerField()
    line_5 = models.IntegerField()
    chng_5 = models.IntegerField()
    line_6 = models.IntegerField()
    chng_6 = models.IntegerField()
    notes = models.CharField(max_length=500, blank=True, null=True)
    conclusion = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return "%d" % self.consultation_id + ":  " + self.query

    class Meta:
        managed = False
        db_table = 'consultation'


class HLinePosition(models.Model):
    h_line_position_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=45)
    meaning = models.CharField(max_length=500)

    class Meta:
        managed = False
        db_table = 'h_line_position'


class Trigram(models.Model):
    trigram_id = models.CharField(primary_key=True, max_length=45)
    description = models.CharField(max_length=500)

    class Meta:
        managed = False
        db_table = 'trigram'


class Hexagram(models.Model):
    hexagram_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=45)
    description = models.CharField(max_length=10000)
    upper_trigram = models.ForeignKey('Trigram', models.DO_NOTHING, db_column='upper_trigram', related_name='ut')
    lower_trigram = models.ForeignKey('Trigram', models.DO_NOTHING, db_column='lower_trigram', related_name='lt')

    class Meta:
        managed = False
        db_table = 'hexagram'


class Line(models.Model):
    line_id = models.IntegerField(primary_key=True)
    description = models.CharField(max_length=500)

    class Meta:
        managed = False
        db_table = 'line'


class HexagramLine(models.Model):
    hexagram_line_id = models.IntegerField(primary_key=True)
    hexagram = models.ForeignKey(Hexagram, models.DO_NOTHING, db_column='hexagram', related_name='h')
    h_line_position = models.ForeignKey(HLinePosition, models.DO_NOTHING, db_column='h_line_position')
    line = models.ForeignKey('Line', models.DO_NOTHING, db_column='line')
    translation = models.CharField(max_length=500)
    commentary = models.CharField(max_length=1000)
    related_hexagram = models.ForeignKey(Hexagram, models.DO_NOTHING, db_column='related_hexagram', related_name='rh')

    class Meta:
        managed = False
        db_table = 'hexagram_line'
        unique_together = (('hexagram', 'h_line_position'),)


class LineChanges(models.Model):
    line_changes_id = models.IntegerField(primary_key=True)
    line_1 = models.IntegerField()
    line_2 = models.IntegerField()
    line_3 = models.IntegerField()
    line_4 = models.IntegerField()
    line_5 = models.IntegerField()
    line_6 = models.IntegerField()
    chng_1 = models.IntegerField()
    chng_2 = models.IntegerField()
    chng_3 = models.IntegerField()
    chng_4 = models.IntegerField()
    chng_5 = models.IntegerField()
    chng_6 = models.IntegerField()
    hexagram = models.ForeignKey(Hexagram, models.DO_NOTHING, db_column='hexagram')

    class Meta:
        managed = False
        db_table = 'line_changes'
        unique_together = (('line_1', 'line_2', 'line_3', 'line_4', 'line_5', 'line_6', 'chng_1', 'chng_2', 'chng_3', 'chng_4', 'chng_5', 'chng_6'),)


class Pair(models.Model):
    hexagram1_id = models.ForeignKey(Hexagram, models.DO_NOTHING, primary_key=True, related_name='h1')
    hexagram2 = models.ForeignKey(Hexagram, models.DO_NOTHING, db_column='hexagram2', related_name='h2')

    class Meta:
        managed = False
        db_table = 'pair'
        unique_together = (('hexagram1_id', 'hexagram2'),)


class TrigramLine(models.Model):
    trigram_line_id = models.IntegerField(primary_key=True)
    trigram = models.ForeignKey(Trigram, models.DO_NOTHING, db_column='trigram')
    t_line_position = models.IntegerField()
    line = models.ForeignKey(Line, models.DO_NOTHING, db_column='line')

    class Meta:
        managed = False
        db_table = 'trigram_line'
        unique_together = (('trigram', 't_line_position'),)

ichingdb/templates/ichingdb/about.html
<p><a href="{% url 'ichingdb:index' %}">Index</a></p>
<h1>About this website and the new technology behind it...</h1>
<p>I have found the I Ching to be an invaluable source of wisdom and insight. I hope this tool will help make it more accessible to others.</p>
<p>This is a minimal prototype of a new "I Ching engine". Just ask a question (or append the first and last hexagram numbers to the URL, such as 12/1/) and it will assemble a complex reading for you.</p>
<p>The front-end website is deliberately minimal, showing only the core functionality. This will be customised in the future.</p>
<p>The purpose of this website is to exhibit the functionality of the back-end engine, which is a relational database (MySQL) with a schema that encodes the structure of the I Ching and the associated text fragments.</p>
<p>This enables one to perform complex readings of the I Ching with ease. SQL queries pull together all the associated text fragments, which are then formatted into a 'reading' using Django to interface with the web.</p>
<p>The prototype has no user-access controls, hence on this demo website updating and deleting are disabled.</p>
<p>All randomly generated readings remain part of the archive and can be referred back to later, however there is no identifying information stored along with them.</p>
<h2><b>Licensing:</b></h2>
<p>This work (excluding the text fragments) is <a href="https://github.com/anandavala/ichingdb/blob/master/LICENSE">unlicensed</a> and free to use and adapt in any way you see fit.</p>
<p>This approach is simple, flexible, customisable and open source. I hope it will evolve from these humble beginnings.</p>
<p>The source files can be found <a href="https://github.com/anandavala/ichingdb/">here</a>.</p>
<p>Some of the text fragments included in the database were scraped from <a href="http://jamesdekorne.com/GBCh/I%20Ching_dl.pdf">The Gnostic Book of Changes</a>. There is no copyright declaration with these.</p>
<p>Most were scraped from the website <a href="http://inthefamilyway.org/iching/">I Ching: Mothering Change</a>, which is based on the work of
<a href="https://ichinglivingchange.org/">Steven Karcher</a>. These are copyrighted.</p>
<p>Note: I have used Steven Karcher's book <a href="https://www.amazon.com/Total-I-Ching-Myths-Change/dp/074993980X/ref=sr_1_1?s=books&ie=UTF8&qid=1436475035&sr=1-1&keywords=Total+I+Ching%3A+Myths+for+Change">Total I Ching: Myths For Change</a>
for many years. I include this text as a sign of respect for his work and out of a desire to provide the best I Ching access to the general public. I only scraped a minimal amount of text and hope there are no copyright issues. If so the text and links can easily be swapped for another set.</p>
<p>Enjoy! :)</p>

ichingdb/templates/ichingdb/consultation_form.html
<p><a href="{% url 'ichingdb:index' %}">Index</a></p>
<p>Just click in the query field, type your query text then hit 'ENTER' or click 'Submit'.</p>
<p>The lines and changing lines will then be randomised using the "3 coin method" (with the 'seed' set using the current time).</p>
<p>All generated consultations are recorded in the archive and can be referred back to later, however there is no identifying information stored along with them.</p>
<p>Alternatively, to look up a reading without generating it randomly, e.g. 12 &rightarrow; 1 just append "12/1/" to the main URL. Or if there are no changing lines in the reading enter the initial hexagram twice, e.g. "12/12/"</p>
<p>Note: do not think of this like querying a search engine, think of it as like asking a wise person or even an omniscient universal consciousness.</p>
<p>If you sincerely seek to live life in accord with the Way and align with the universal flow, then the I Ching will speak clearly to give you guidance and insight.</p>
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

ichingdb/templates/ichingdb/path02.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<title>Example Path 2</title>
</head>
<body>
<p><a href="{% url 'ichingdb:index' %}">Index</a></p>
<h1 align="center">Example Path 2</h1>
<p>Below is an example of a path through the I Ching's space of meaning, which can be interpreted as an outline of a story.</p>
<p><br/>

</p>
<table border cellpadding="4" cellspacing="0">
	<tr>
		<th>
			<p>Initial</p>
		</th>
		<th>
			<p>Outcome</p>
		</th>
		<th>
			<p>Link</p>
		</th>
		<th>
			<p>Changing Line Text</p>
		</th>
	</tr>
	<tr valign="top">
		<td>
			<p>䷌ 13 Harmonizing People</p>
		</td>
		<td>
			<p>䷘ 25 Disentangling</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}13/25/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>Retreat and prepare a countermove. This may seem like a
			disaster but if you move with it you can eliminate the old
			negativity. This is not the time for aggression or insistence on
			your ideas. Accumulate the strength to carry heavy loads and
			confront difficult situations. Proceed step by step. Gather energy
			for a decisive new move.</p>
		</td>
	</tr>
	<tr valign="top">
		<td>
			<p>䷘ 25 Disentangling</p>
		</td>
		<td>
			<p>䷉ 10 Treading</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}25/10/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>If you realize what this time means, all your plans will
			succeed. Smooth the way from the shadows. You have a hidden
			connection that binds you to others. Empty your mind of immediate
			goals. Supportive friends will soon arrive. Step out to meet the
			new destiny. You can confront and disable a powerful and
			malevolent opponent. Gather energy for a decisive new move.</p>
		</td>
	</tr>
	<tr valign="top">
		<td>
			<p>䷉ 10 Treading</p>
		</td>
		<td>
			<p>䷥ 38 Diverging</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}10/38/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>You must decisively separate yourself from a dangerous
			influence. Have no fear. Face the danger. Have no concern for
			glory or achievements. Locate yourself in the center and nourish
			your people. All cause for discord and sorrow will disappear. Step
			outside the norms and re-imagine the situation. Co-operate with
			the ongoing process of change.</p>
		</td>
	</tr>
	<tr valign="top">
		<td>
			<p>䷥ 38 Diverging</p>
		</td>
		<td>
			<p>䷔ 21 Biting Through</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}38/21/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>In an unexpected way you meet someone or something of great
			importance. Let this influence enter your heart. Though you may
			feel your gifts are small, bite through the obstacles to union.
			Act from your heart. You can create a warm and inspiring
			atmosphere. Care for other people. Gather energy for a decisive
			new move.</p>
		</td>
	</tr>
	<tr valign="top">
		<td>
			<p>䷔ 21 Biting Through</p>
		</td>
		<td>
			<p>䷝ 30 Radiance / Visionary</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}21/30/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>Biting through to union you encounter something old and
			poisonous. Bring it out. Beat your drums or you will end up
			lamenting like a very old person. The distress you feel will soon
			disappear. Those who approach you now are not outlaws. Treat them
			with great respect and seek an alliance. Do not be afraid to act
			alone. You are connected with a creative force.</p>
		</td>
	</tr>
	<tr valign="top">
		<td>
			<p>䷝ 30 Radiance / Visionary</p>
		</td>
		<td>
			<p>䷍ 14 Great Being</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}30/14/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>You have found the connection. Light and power surge up from
			below. As you venture into danger you will get what you need by
			being flexible and adaptable. Gather people around you and do not
			impose your will. You are at the center of this group. Do not let
			this chance slip through your fingers. Use an inspiring idea to
			carry your desires. Be resolute. You are connected with a creative
			force.</p>
		</td>
	</tr>
</table>
<p><br/>

</p>
<p>In this example each hexagram has only a single changing line. And although there is a complex reading for each transition only 
the text for the changing line is shown to give an idea of the nature of the transition.</p>
<p>This is just one of many thousands of possible paths through this space of meaning. It serves as an example of how the hexagrams connect via changing lines
to form a complex network of meaning. This is an alternate way to get to know the wisdom encoded within the I Ching. Each path can also be elaborated into stories
to illustrate the wisdom and provide guidance to help people navigate their way through life.</p>
<p>Note: the above path through the I Ching space was assembled from the <a href="{% url 'ichingdb:paths' %}">path</a> query and results shown below.</p>
<p><br/>

</p>
<table border cellpadding="2" cellspacing="2">
	<tr>
		<th>
			<p>NChng</p>
		</th>
		<th>
			<p>Initial</p>
		</th>
		<th>
			<p>Final</p>
		</th>
		<th>
			<p>NSteps</p>
		</th>
	</tr>
	<tr>
		<td>
			<p>1</p>
		</td>
		<td>
			<p>13</p>
		</td>
		<td>
			<p>14</p>
		</td>
		<td>
			<p>6</p>
		</td>
	</tr>
</table>
<p><br/>

</p>
<table border cellpadding="2" cellspacing="2">
	<tr>
		<td>
			<p>413</p>
		</td>
		<td>
			<p>䷌ 13 Harmonizing People</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}13/25/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷘ 25 Disentangling</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}25/10/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷉ 10 Treading</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}10/38/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷥ 38 Diverging</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}38/21/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷔ 21 Biting Through</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}21/30/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷝ 30 Radiance / Visionary</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}30/14/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷍ 14 Great Being</p>
		</td>
	</tr>
</table>
<p><br/>

</p>
</body>
</html>

ichingdb/templates/ichingdb/path03.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<title>Example Path 3</title>
</head>
<body>
<p><a href="{% url 'ichingdb:index' %}">Index</a></p>
<h1 align="center">Example Path 3</h1>
<p>Below is an example of a path through the I Ching's space of meaning, which can be interpreted as an outline of a story.</p>
<p><br/>

</p>
<table border cellpadding="4" cellspacing="0">
	<tr>
		<th>
			<p>Initial</p>
		</th>
		<th>
			<p>Outcome</p>
		</th>
		<th>
			<p>Link</p>
		</th>
		<th>
			<p>Changing Line Text</p>
		</th>
	</tr>
	<tr valign="top">
		<td>
			<p>䷲ 51 Shake / Groundbreaker</p>
		</td>
		<td>
			<p>䷏ 16 Providing for</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}51/16/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>This is a profound shock. Everything is turned upside down. Do
			not call out for help now. Cut through pride and complication and
			set the armies marching. If you meet people with generosity and
			care you can signal to your true kin. Step outside the norms.
			These goings and comings will release the energy bound up in the
			past. Gather energy for a decisive new move.</p>
		</td>
	</tr>
	<tr valign="top">
		<td>
			<p>䷏ 16 Providing for</p>
		</td>
		<td>
			<p>䷢ 35 Flourishing</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}16/35/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>Work on in the dark to provide for the future. Keep your pride
			out of the way. Your inner work will call out to others. Master
			your words and you can influence people. Attack the old ways and
			you will soon emerge into the light. These goings and comings
			release energy bound up in the past. Step outside the norms.
			Gather energy for the decisive new move.</p>
		</td>
	</tr>
	<tr valign="top">
		<td>
			<p>䷢ 35 Flourishing</p>
		</td>
		<td>
			<p>䷿ 64 Not Yet Crossing</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}35/64/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>You feel anxious and sorrowful. Do not fear. Take on this
			arduous task and receive the blessing of the feminine powers. Let
			yourself be lured into action. Your sincerity and dedication are
			what count. The situation seems difficult, but you will survive.
			This will bring profit and insight in the end. Gather energy for a
			decisive new move.</p>
		</td>
	</tr>
	<tr valign="top">
		<td>
			<p>䷿ 64 Not Yet Crossing</p>
		</td>
		<td>
			<p>䷧ 40 Deliverance / Liberating</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}64/40/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>You have a great connection but start slowly. Let yourself be
			lured on. Difficulties are going, praise and ease are coming. Pull
			back and join with others and you will capture the force opposing
			your plans and desires. There is nothing that will not benefit.
			These goings and comings release the energy now bound up in the
			past. Cooperate with the on-going process of change.</p>
		</td>
	</tr>
	<tr valign="top">
		<td>
			<p>䷧ 40 Deliverance / Liberating</p>
		</td>
		<td>
			<p>䷵ 54 Marrying Maiden</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}40/54/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>Act on your plans. You are in the right position. Difficulties
			are going, ripeness and abundance are coming. Talk to those who
			can connect you with what is great. Now is the time to put things
			in order. If you let yourself be led you can realize your hidden
			potential. Co-operate with the ongoing process of change.</p>
		</td>
	</tr>
	<tr valign="top">
		<td>
			<p>䷵ 54 Marrying Maiden</p>
		</td>
		<td>
			<p>䷡ 34 Great Invigorating</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}54/34/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>You are in a subservient place. Have patience. In the end you
			will reverse things and gain the strategic position. You are
			confronting a troublesome past experience. Retreat to rekindle
			your love for people. This is a resting-place and a portent of
			future happiness. If you use force now you will only be entangled.
			You are coupled with a creative force.</p>
		</td>
	</tr>
</table>
<p><br/>

</p>
<p>In this example each hexagram has only a single changing line. And although there is a complex reading for each transition only 
the text for the changing line is shown to give an idea of the nature of the transition.</p>
<p>This is just one of many thousands of possible paths through this space of meaning. It serves as an example of how the hexagrams connect via changing lines
to form a complex network of meaning. This is an alternate way to get to know the wisdom encoded within the I Ching. Each path can also be elaborated into stories
to illustrate the wisdom and provide guidance to help people navigate their way through life.</p>
<p>Note: the above path through the I Ching space was assembled from the <a href="{% url 'ichingdb:paths' %}">path</a> query and results shown below.</p>
<p><br/>

</p>
<table border cellpadding="2" cellspacing="2">
	<tr>
		<th>
			<p>NChng</p>
		</th>
		<th>
			<p>Initial</p>
		</th>
		<th>
			<p>Final</p>
		</th>
		<th>
			<p>NSteps</p>
		</th>
	</tr>
	<tr>
		<td>
			<p>1</p>
		</td>
		<td>
			<p>51</p>
		</td>
		<td>
			<p>34</p>
		</td>
		<td>
			<p>6</p>
		</td>
	</tr>
</table>
<p><br/>

</p>
<table border cellpadding="2" cellspacing="2">
	<tr>
		<td>
			<p>46</p>
		</td>
		<td>
			<p>䷲ 51 Shake / Groundbreaker</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}51/16/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷏ 16 Providing for</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}16/35/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷢ 35 Flourishing</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}35/64/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷿ 64 Not Yet Crossing</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}64/40/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷧ 40 Deliverance / Liberating</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}40/54/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷵ 54 Marrying Maiden</p>
		</td>
		<td>
			<p><a href="{% url 'ichingdb:index' %}54/34/" target="_blank">Reading</a></p>
		</td>
		<td>
			<p>䷡ 34 Great Invigorating</p>
		</td>
	</tr>
</table>
<p><br/>

</p>
</body>
</html>

ichingdb/templates/ichingdb/related.html
<!DOCTYPE html>
<html>
<head>
<style>table, th, td {
    border: 1px solid black; 
    border-collapse: collapse; 
    padding: 5px;
}
</style>
</head>
<body>
<h1>Find hexagrams related to a particular hexagram.</h1>
<p>Explore the space of possible evolutions from a given state.</p>
<p>Valid values below are an integer from 1 to 64 (initial hexagram) & a list of integers between 0 and 6 (list of step lengths to include).</p>
<p>A step length is the number of changing lines involved in a transition.</p>
<form method="POST" action="">
{% csrf_token %}
<table>
<tr><th>Initial Hexagram</th><th>Step Lengths</th></tr>
<tr><td><input type="text" name="initial" value="1"></td><td><input type="text" name="levels" value="0,1,2,3,4,5,6"></td></tr>
</table>
<p><button type="submit">Related</button></p>
</form>
<p>Return to <a href="{% url 'ichingdb:index' %}">Index</a></p>
<h2>Example searches:</h2>
<ul>
<li>
<p>Find all readings with initial hexagram 47 Confining and exactly 2 or 3 changing lines.</p>
<table>
<tr><th>Initial</th><th>Levels</th></tr>
<tr><td>47</td><td>2,3</td></tr>
</table>
</li>
<li>
<p>Find all readings with initial hexagram 2 Field and any number of changing lines.</p>
<table>
<tr><th>Initial</th><th>Levels</th></tr>
<tr><td>2</td><td>0,1,2,3,4,5,6</td></tr>
</table>
</li>
<li>
<p>Find all readings with initial hexagram 15 Humbling and exactly 1 changing line.</p>
<table>
<tr><th>Initial</th><th>Levels</th></tr>
<tr><td>15</td><td>1</td></tr>
</table>
</li>
</ul>
</body>